name: Deploy to Heroku Production

on:
  push:
    tags:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: heroku
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_STAGING_API_KEY}}
          heroku_app_name: 'mysocialappmsa'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: 'api'
