name: Deploy to Heroku Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: heroku
    steps:
      - uses: actions/checkout@v2
      - name: Setup heroku remote
        run: |
          git remote add heroku '${{secrets.HEROKU_PRODUCTION_GIT_URL}}'
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_PRODUCTION_API_KEY}}
          heroku_app_name: 'mysocialappmsa'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: 'api'
