name: Deploy to Heroku Staging

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: heroku
    steps:
      - uses: actions/checkout@v2
      - name: Setup heroku remote
        run: |
          git remote add heroku '${{secrets.HEROKU_STAGING_GIT_URL}}'
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_STAGING_API_KEY}}
          heroku_app_name: 'immense-chamber-72842'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: 'api'
